"""Runtime adapter contract for Iris Core."""

from __future__ import annotations

from typing import Any, Protocol


class RuntimeAdapter(Protocol):
    kind: str

    def list_agents(self) -> list[dict[str, Any]]: ...
    def get_agent(self, agent_id: str) -> dict[str, Any] | None: ...
    def create_agent(self, name: str, metadata: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def clone_agent(self, source_agent: dict[str, Any], name: str) -> dict[str, Any]: ...
    def rename_agent(self, agent: dict[str, Any], name: str) -> dict[str, Any]: ...
    def activate_agent(self, agent: dict[str, Any]) -> dict[str, Any]: ...
    def delete_agent(self, agent: dict[str, Any]) -> dict[str, Any]: ...
    def agent_memory(self, agent: dict[str, Any]) -> dict[str, Any]: ...
    def save_agent_memory(
        self,
        agent: dict[str, Any],
        file: str,
        content: str,
        expected_updated_at: int | None = None,
    ) -> dict[str, Any]: ...
    def reset_agent_memory(self, agent: dict[str, Any], file: str) -> dict[str, Any]: ...
    def list_agent_skills(self, agent: dict[str, Any]) -> dict[str, Any]: ...
    def get_agent_skill(self, agent: dict[str, Any], skill_id: str) -> dict[str, Any]: ...
    def create_agent_skill(self, agent: dict[str, Any], payload: dict[str, Any]) -> dict[str, Any]: ...
    def save_agent_skill(self, agent: dict[str, Any], skill_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_conversations(self, agent: dict[str, Any], limit: int = 80) -> list[dict[str, Any]]: ...
    def get_conversation(
        self,
        agent: dict[str, Any],
        external_id: str = "",
        *,
        chat_id: str = "",
        conversation_id: str = "",
    ) -> dict[str, Any] | None: ...
    def rename_conversation(
        self,
        agent: dict[str, Any],
        conversation: dict[str, Any],
        title: str,
    ) -> dict[str, Any]: ...
    def delete_conversation(
        self,
        agent: dict[str, Any],
        conversation: dict[str, Any],
    ) -> dict[str, Any]: ...
    def get_conversation_messages(
        self,
        agent: dict[str, Any],
        external_id: str = "",
        *,
        chat_id: str = "",
        conversation_id: str = "",
    ) -> tuple[list[dict[str, Any]], str | None]: ...
    def probe(self, profile: str = "default") -> dict[str, Any]: ...
    def send_message(self, **kwargs: Any) -> dict[str, Any]: ...
    def models(self, profile: str, max_models: int = 100) -> dict[str, Any]: ...
    def slash_commands(self, profile: str) -> dict[str, Any]: ...
    def slash_complete(self, profile: str, text: str, limit: int = 30) -> dict[str, Any]: ...
    def list_automations(self, profile: str) -> dict[str, Any]: ...
    def create_automation(self, automation: dict[str, Any]) -> dict[str, Any]: ...
    def update_automation(self, external_job_id: str, updates: dict[str, Any]) -> dict[str, Any]: ...
    def delete_automation(self, external_job_id: str) -> dict[str, Any]: ...
    def control_automation(self, external_job_id: str, action: str) -> dict[str, Any]: ...
